create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default 'Administrador',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key check (id ~ '^[a-z0-9_-]{1,80}$'),
  title text not null check (char_length(title) between 1 and 160),
  variant_name text not null check (char_length(variant_name) between 1 and 80),
  price numeric(10,2) not null check (price >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  image_url text,
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.checkout_addons (
  id text primary key check (id ~ '^[a-z0-9_-]{1,80}$'),
  title text not null check (char_length(title) between 1 and 160),
  old_price numeric(10,2) check (old_price is null or old_price >= 0),
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.checkout_shipping_methods (
  id text primary key check (id ~ '^[a-z0-9_-]{1,80}$'),
  title text not null check (char_length(title) between 1 and 100),
  description text not null check (char_length(description) between 1 and 160),
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null check (char_length(customer_name) between 2 and 120),
  customer_email text not null check (customer_email ~* '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'),
  phone text not null check (char_length(phone) between 10 and 20),
  customer_tax_id text not null check (customer_tax_id ~ '^[0-9]{11}([0-9]{3})?$'),
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 8),
  addons jsonb not null default '[]'::jsonb,
  quantity integer not null default 1 check (quantity between 1 and 100),
  amount numeric(10,2) not null default 0 check (amount >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  status text not null default 'pending' check (status in ('pending','paid','processing','cancelled','fulfilled')),
  shipping_address text,
  city text,
  postal_code text,
  shipping_method text not null default 'free',
  shipping_amount numeric(10,2) not null default 0,
  payment_reference uuid unique,
  gateway text check (gateway is null or gateway in ('primecash', 'titans', 'manual_pix')),
  gateway_checkout_id text,
  gateway_status text,
  pix_txid text,
  paid_at timestamptz,
  confirmed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gateway_settings (
  provider text primary key check (provider in ('primecash', 'titans', 'manual_pix')),
  display_name text not null,
  active boolean not null default true,
  pix_key text,
  pix_key_type text check (pix_key_type is null or pix_key_type in ('random', 'cpf', 'cnpj', 'phone', 'email')),
  pix_receiver_name text,
  pix_receiver_city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists orders_pix_txid_unique_idx
  on public.orders (pix_txid) where pix_txid is not null;

create table if not exists public.tracking_events (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 8 and 100),
  event_name text not null check (event_name in ('product_view','cart_open','checkout_view','checkout_started')),
  page_url text not null check (char_length(page_url) between 1 and 500),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.prepare_cacarola_order()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  input_item jsonb;
  input_addon jsonb;
  catalog_item public.products%rowtype;
  catalog_addon public.checkout_addons%rowtype;
  delivery_method public.checkout_shipping_methods%rowtype;
  normalized_items jsonb := '[]'::jsonb;
  normalized_addons jsonb := '[]'::jsonb;
  seen_addons text[] := array[]::text[];
  addon_id text;
  item_quantity integer;
  calculated_total numeric(10,2) := 0;
  calculated_quantity integer := 0;
begin
  new.customer_email := lower(trim(new.customer_email));
  new.customer_name := trim(new.customer_name);
  new.phone := regexp_replace(new.phone, '[^0-9]', '', 'g');
  new.customer_tax_id := regexp_replace(new.customer_tax_id, '[^0-9]', '', 'g');

  for input_item in select value from jsonb_array_elements(new.items)
  loop
    item_quantity := coalesce((input_item ->> 'quantity')::integer, 0);
    if item_quantity < 1 or item_quantity > 99 then
      raise exception 'Quantidade inválida';
    end if;

    select * into catalog_item
    from public.products
    where id = input_item ->> 'product_id' and active = true;

    if not found then
      raise exception 'Produto indisponível';
    end if;

    if catalog_item.stock_quantity is not null and catalog_item.stock_quantity < item_quantity then
      raise exception 'Estoque insuficiente';
    end if;

    normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
      'product_id', catalog_item.id,
      'title', catalog_item.title,
      'variant_name', catalog_item.variant_name,
      'unit_price', catalog_item.price,
      'quantity', item_quantity
    ));
    calculated_quantity := calculated_quantity + item_quantity;
    calculated_total := calculated_total + (catalog_item.price * item_quantity);
  end loop;

  if jsonb_typeof(coalesce(new.addons, '[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(new.addons, '[]'::jsonb)) > 3 then
    raise exception 'Ofertas adicionais inválidas';
  end if;

  for input_addon in select value from jsonb_array_elements(coalesce(new.addons, '[]'::jsonb))
  loop
    addon_id := input_addon ->> 'addon_id';
    if addon_id is null or addon_id = any(seen_addons) then
      raise exception 'Oferta adicional inválida';
    end if;

    select * into catalog_addon
    from public.checkout_addons
    where id = addon_id and active = true;

    if not found then
      raise exception 'Oferta adicional indisponível';
    end if;

    seen_addons := array_append(seen_addons, addon_id);
    normalized_addons := normalized_addons || jsonb_build_array(jsonb_build_object(
      'addon_id', catalog_addon.id,
      'title', catalog_addon.title,
      'unit_price', catalog_addon.price,
      'quantity', 1
    ));
    calculated_quantity := calculated_quantity + 1;
    calculated_total := calculated_total + catalog_addon.price;
  end loop;

  select * into delivery_method
  from public.checkout_shipping_methods
  where id = new.shipping_method and active = true;

  if not found then
    raise exception 'Forma de entrega indisponível';
  end if;

  new.items := normalized_items;
  new.addons := normalized_addons;
  new.shipping_amount := delivery_method.price;
  new.quantity := calculated_quantity;
  new.amount := calculated_total + delivery_method.price;
  new.currency := 'BRL';
  new.status := 'pending';
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists prepare_cacarola_order_before_insert on public.orders;
create trigger prepare_cacarola_order_before_insert
before insert on public.orders
for each row execute function public.prepare_cacarola_order();

alter table public.admin_users enable row level security;
alter table public.products enable row level security;
alter table public.checkout_addons enable row level security;
alter table public.checkout_shipping_methods enable row level security;
alter table public.orders enable row level security;
alter table public.tracking_events enable row level security;
alter table public.gateway_settings enable row level security;

create policy "admins can read own membership" on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));

create policy "active products are public" on public.products
for select to anon using (active = true);
create policy "active checkout addons are public" on public.checkout_addons
for select to anon, authenticated using (active = true);
create policy "active shipping methods are public" on public.checkout_shipping_methods
for select to anon, authenticated using (active = true);
create policy "authenticated users read products" on public.products
for select to authenticated using (active = true or exists (
  select 1 from public.admin_users au where au.user_id = (select auth.uid())
));
create policy "admins insert products" on public.products
for insert to authenticated with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins update products" on public.products
for update to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())))
with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins delete products" on public.products
for delete to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

create policy "public checkout creates pending orders" on public.orders
for insert to anon, authenticated with check (status = 'pending' and amount >= 0);
create policy "admins read orders" on public.orders
for select to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins update orders" on public.orders
for update to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())))
with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

create policy "public records storefront events" on public.tracking_events
for insert to anon, authenticated with check (event_name in ('product_view','cart_open','checkout_view','checkout_started'));
create policy "admins read events" on public.tracking_events
for select to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

create policy "admins read gateway settings" on public.gateway_settings
for select to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins update gateway settings" on public.gateway_settings
for update to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())))
with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

revoke all on public.admin_users, public.products, public.checkout_addons, public.checkout_shipping_methods, public.orders, public.tracking_events, public.gateway_settings from anon, authenticated;
grant select on public.products to anon, authenticated;
grant select on public.checkout_addons, public.checkout_shipping_methods to anon, authenticated;
grant insert on public.orders, public.tracking_events to anon, authenticated;
grant select on public.admin_users, public.orders, public.tracking_events to authenticated;
grant insert, update, delete on public.products to authenticated;
grant update on public.orders to authenticated;
grant select, update on public.gateway_settings to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.products (id,title,variant_name,price,currency,image_url,stock_quantity,active,sort_order)
values
  ('marmore','Kit 10 Peças Colinox','Mármore',87.90,'BRL','cart-marmore.png',null,true,1),
  ('quartzo','Kit 10 Peças Colinox','Quartzo',79.90,'BRL','assets/products/quartzo.webp',null,true,2),
  ('grafite','Kit 10 Peças Colinox','Grafite',89.90,'BRL','assets/products/grafite.webp',null,true,3),
  ('oliva','Kit 10 Peças Colinox','Oliva',89.90,'BRL','assets/products/oliva.webp',null,true,4)
on conflict (id) do update set
  title = excluded.title,
  variant_name = excluded.variant_name,
  price = excluded.price,
  currency = excluded.currency,
  image_url = coalesce(excluded.image_url, public.products.image_url),
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.checkout_addons (id,title,old_price,price,image_url,active,sort_order) values
  ('jantar','Jogo de Jantar 10 Peças Oxford Ryo Maresia',189.90,46.20,'/assets/checkout/order-bump-jantar.png',true,10),
  ('potes','Kit 10 Potes de Vidro Herméticos Colinox',139.90,36.45,'/assets/checkout/order-bump-potes.png',true,20),
  ('panela','Panela de Pressão Colinox Antiaderente 4,2L',219.90,55.47,'/assets/checkout/order-bump-panela.png',true,30)
on conflict (id) do update set title=excluded.title,old_price=excluded.old_price,price=excluded.price,image_url=excluded.image_url,active=excluded.active,sort_order=excluded.sort_order,updated_at=now();

insert into public.checkout_shipping_methods (id,title,description,price,image_url,active,sort_order) values
  ('free','Frete Grátis','Entrega em 10 a 12 dias',0,'/assets/checkout/shipping-free.jpg',true,10),
  ('jadlog','JADLOG','Entrega em até 5 dias úteis',18.47,'/assets/checkout/shipping-jadlog.jpg',true,20),
  ('sedex-12','SEDEX 12','Entrega de 12h a 24h',33.40,'/assets/checkout/shipping-sedex.png',true,30)
on conflict (id) do update set title=excluded.title,description=excluded.description,price=excluded.price,image_url=excluded.image_url,active=excluded.active,sort_order=excluded.sort_order,updated_at=now();

insert into public.gateway_settings (provider, display_name, active)
values ('primecash', 'PrimeCash Brasil', true)
on conflict (provider) do nothing;

insert into public.gateway_settings (provider, display_name, active)
values ('titans', 'Titans Gateway', false)
on conflict (provider) do nothing;

insert into public.gateway_settings (provider, display_name, active)
values ('manual_pix', 'Pix Manual', false)
on conflict (provider) do nothing;

create unique index if not exists gateway_settings_single_active_idx
  on public.gateway_settings ((active)) where active;

create or replace function public.set_active_gateway(p_provider text, p_active boolean)
returns void language plpgsql security invoker set search_path = ''
as $$
begin
  if not exists (select 1 from public.admin_users where user_id = (select auth.uid())) then
    raise exception 'Acesso administrativo não autorizado';
  end if;
  if p_provider not in ('primecash', 'titans', 'manual_pix') then raise exception 'Gateway inválido'; end if;
  if p_active then
    update public.gateway_settings set active = false, updated_at = now() where provider <> p_provider and active;
  end if;
  update public.gateway_settings set active = p_active, updated_at = now() where provider = p_provider;
end;
$$;

create or replace function public.set_primecash_secret(p_secret text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  secret_id uuid;
begin
  if p_secret is null or char_length(trim(p_secret)) < 12 or char_length(p_secret) > 500 then
    raise exception 'Secret Key inválida';
  end if;
  select id into secret_id from vault.secrets where name = 'primecash_secret_key';
  if secret_id is null then
    perform vault.create_secret(trim(p_secret), 'primecash_secret_key', 'PrimeCash API Secret Key');
  else
    perform vault.update_secret(secret_id, trim(p_secret), 'primecash_secret_key', 'PrimeCash API Secret Key');
  end if;
end;
$$;

create or replace function public.get_primecash_secret()
returns text language sql stable security definer set search_path = ''
as $$ select decrypted_secret from vault.decrypted_secrets where name = 'primecash_secret_key' limit 1; $$;

create or replace function public.has_primecash_secret()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from vault.secrets where name = 'primecash_secret_key'); $$;

revoke all on function public.set_primecash_secret(text) from public, anon, authenticated;
revoke all on function public.get_primecash_secret() from public, anon, authenticated;
revoke all on function public.has_primecash_secret() from public, anon, authenticated;
grant execute on function public.set_primecash_secret(text) to service_role;
grant execute on function public.get_primecash_secret() to service_role;
grant execute on function public.has_primecash_secret() to service_role;

create or replace function public.set_titans_secret(p_secret text)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
begin
  if p_secret is null or char_length(trim(p_secret)) < 12 or char_length(p_secret) > 500 then raise exception 'API Key inválida'; end if;
  select id into secret_id from vault.secrets where name = 'titans_api_key';
  if secret_id is null then
    perform vault.create_secret(trim(p_secret), 'titans_api_key', 'Titans Gateway Payment API Key');
  else
    perform vault.update_secret(secret_id, trim(p_secret), 'titans_api_key', 'Titans Gateway Payment API Key');
  end if;
end;
$$;

create or replace function public.get_titans_secret()
returns text language sql stable security definer set search_path = ''
as $$ select decrypted_secret from vault.decrypted_secrets where name = 'titans_api_key' limit 1; $$;

create or replace function public.has_titans_secret()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists (select 1 from vault.secrets where name = 'titans_api_key'); $$;

create or replace function public.set_titans_webhook_secret(p_secret text)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
begin
  if p_secret is null or char_length(trim(p_secret)) < 12 or char_length(p_secret) > 500 then raise exception 'Webhook Secret inválido'; end if;
  select id into secret_id from vault.secrets where name = 'titans_webhook_secret';
  if secret_id is null then
    perform vault.create_secret(trim(p_secret), 'titans_webhook_secret', 'Titans Gateway Webhook HMAC Secret');
  else
    perform vault.update_secret(secret_id, trim(p_secret), 'titans_webhook_secret', 'Titans Gateway Webhook HMAC Secret');
  end if;
end;
$$;

create or replace function public.get_titans_webhook_secret()
returns text language sql stable security definer set search_path = ''
as $$ select decrypted_secret from vault.decrypted_secrets where name = 'titans_webhook_secret' limit 1; $$;

revoke all on function public.set_active_gateway(text, boolean) from public, anon, authenticated;
grant execute on function public.set_active_gateway(text, boolean) to authenticated;
revoke all on function public.set_titans_secret(text) from public, anon, authenticated;
revoke all on function public.get_titans_secret() from public, anon, authenticated;
revoke all on function public.has_titans_secret() from public, anon, authenticated;
revoke all on function public.set_titans_webhook_secret(text) from public, anon, authenticated;
revoke all on function public.get_titans_webhook_secret() from public, anon, authenticated;
grant execute on function public.set_titans_secret(text) to service_role;
grant execute on function public.get_titans_secret() to service_role;
grant execute on function public.has_titans_secret() to service_role;
grant execute on function public.set_titans_webhook_secret(text) to service_role;
grant execute on function public.get_titans_webhook_secret() to service_role;

create table if not exists public.marketing_integrations (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('google', 'meta', 'tiktok')),
  name text not null check (char_length(name) between 2 and 80),
  tracking_id text not null check (char_length(tracking_id) between 2 and 200),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  integration_id uuid not null references public.marketing_integrations(id) on delete cascade,
  event_name text not null default 'purchase' check (event_name = 'purchase'),
  status text not null default 'processing' check (status in ('processing', 'delivered', 'failed')),
  response_status integer,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, integration_id, event_name)
);

alter table public.marketing_integrations enable row level security;
alter table public.marketing_deliveries enable row level security;
create policy "Admins can read marketing integrations" on public.marketing_integrations for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Admins can read marketing deliveries" on public.marketing_deliveries for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create or replace function public.set_marketing_secret(p_integration_id uuid, p_secret text)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
declare secret_name text := 'marketing_integration_' || p_integration_id::text;
begin
  if p_secret is null or char_length(trim(p_secret)) < 8 or char_length(p_secret) > 1000 then raise exception 'Credencial de rastreamento inválida'; end if;
  if not exists (select 1 from public.marketing_integrations where id = p_integration_id) then raise exception 'Integração não encontrada'; end if;
  select id into secret_id from vault.secrets where name = secret_name;
  if secret_id is null then perform vault.create_secret(trim(p_secret), secret_name, 'Credencial server-side de rastreamento');
  else perform vault.update_secret(secret_id, trim(p_secret), secret_name, 'Credencial server-side de rastreamento'); end if;
end;
$$;
create or replace function public.get_marketing_secret(p_integration_id uuid) returns text language sql stable security definer set search_path = '' as $$ select decrypted_secret from vault.decrypted_secrets where name = 'marketing_integration_' || p_integration_id::text limit 1; $$;
create or replace function public.delete_marketing_secret(p_integration_id uuid) returns void language plpgsql security definer set search_path = '' as $$ declare secret_id uuid; begin select id into secret_id from vault.secrets where name = 'marketing_integration_' || p_integration_id::text; if secret_id is not null then delete from vault.secrets where id = secret_id; end if; end; $$;
create or replace function public.claim_marketing_delivery(p_order_id bigint, p_integration_id uuid) returns bigint language plpgsql security definer set search_path = '' as $$ declare delivery_id bigint; begin insert into public.marketing_deliveries (order_id, integration_id, event_name, status) values (p_order_id, p_integration_id, 'purchase', 'processing') on conflict (order_id, integration_id, event_name) do update set status = 'processing', response_status = null, last_error = null, updated_at = now() where public.marketing_deliveries.status = 'failed' returning id into delivery_id; return delivery_id; end; $$;
revoke all on function public.set_marketing_secret(uuid, text) from public, anon, authenticated;
revoke all on function public.get_marketing_secret(uuid) from public, anon, authenticated;
revoke all on function public.delete_marketing_secret(uuid) from public, anon, authenticated;
revoke all on function public.claim_marketing_delivery(bigint, uuid) from public, anon, authenticated;
grant execute on function public.set_marketing_secret(uuid, text) to service_role;
grant execute on function public.get_marketing_secret(uuid) to service_role;
grant execute on function public.delete_marketing_secret(uuid) to service_role;
grant execute on function public.claim_marketing_delivery(bigint, uuid) to service_role;
grant select on public.marketing_integrations, public.marketing_deliveries to authenticated;
