create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default 'Administrador',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key check (id ~ '^[a-z0-9_-]{1,80}$'),
  title text not null check (char_length(title) between 1 and 160),
  variant_name text not null check (char_length(variant_name) between 1 and 80),
  price numeric(10,2) not null check (price >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  image_url text,
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null check (char_length(customer_name) between 2 and 120),
  customer_email text not null check (customer_email ~* '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'),
  phone text not null check (char_length(phone) between 10 and 20),
  customer_tax_id text not null check (customer_tax_id ~ '^[0-9]{11}([0-9]{3})?$'),
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 8),
  quantity integer not null default 1 check (quantity between 1 and 100),
  amount numeric(10,2) not null default 0 check (amount >= 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  status text not null default 'pending' check (status in ('pending','paid','processing','cancelled','fulfilled')),
  shipping_address text,
  city text,
  postal_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tracking_events (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 8 and 100),
  event_name text not null check (event_name in ('product_view','cart_open','checkout_view','checkout_started')),
  page_url text not null check (char_length(page_url) between 1 and 500),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.prepare_cacarola_order()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  input_item jsonb;
  catalog_item public.products%rowtype;
  normalized_items jsonb := '[]'::jsonb;
  item_quantity integer;
  calculated_total numeric(10,2) := 0;
  calculated_quantity integer := 0;
begin
  new.customer_email := lower(trim(new.customer_email));
  new.customer_name := trim(new.customer_name);
  new.phone := regexp_replace(new.phone, '[^0-9]', '', 'g');
  new.customer_tax_id := regexp_replace(new.customer_tax_id, '[^0-9]', '', 'g');

  for input_item in select value from jsonb_array_elements(new.items)
  loop
    item_quantity := coalesce((input_item ->> 'quantity')::integer, 0);
    if item_quantity < 1 or item_quantity > 99 then
      raise exception 'Quantidade inválida';
    end if;

    select * into catalog_item
    from public.products
    where id = input_item ->> 'product_id' and active = true;

    if not found then
      raise exception 'Produto indisponível';
    end if;

    if catalog_item.stock_quantity is not null and catalog_item.stock_quantity < item_quantity then
      raise exception 'Estoque insuficiente';
    end if;

    normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
      'product_id', catalog_item.id,
      'title', catalog_item.title,
      'variant_name', catalog_item.variant_name,
      'unit_price', catalog_item.price,
      'quantity', item_quantity
    ));
    calculated_quantity := calculated_quantity + item_quantity;
    calculated_total := calculated_total + (catalog_item.price * item_quantity);
  end loop;

  new.items := normalized_items;
  new.quantity := calculated_quantity;
  new.amount := calculated_total;
  new.currency := 'BRL';
  new.status := 'pending';
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists prepare_cacarola_order_before_insert on public.orders;
create trigger prepare_cacarola_order_before_insert
before insert on public.orders
for each row execute function public.prepare_cacarola_order();

alter table public.admin_users enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.tracking_events enable row level security;

create policy "admins can read own membership" on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));

create policy "active products are public" on public.products
for select to anon using (active = true);
create policy "authenticated users read products" on public.products
for select to authenticated using (active = true or exists (
  select 1 from public.admin_users au where au.user_id = (select auth.uid())
));
create policy "admins insert products" on public.products
for insert to authenticated with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins update products" on public.products
for update to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())))
with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins delete products" on public.products
for delete to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

create policy "public checkout creates pending orders" on public.orders
for insert to anon, authenticated with check (status = 'pending' and amount >= 0);
create policy "admins read orders" on public.orders
for select to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));
create policy "admins update orders" on public.orders
for update to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())))
with check (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

create policy "public records storefront events" on public.tracking_events
for insert to anon, authenticated with check (event_name in ('product_view','cart_open','checkout_view','checkout_started'));
create policy "admins read events" on public.tracking_events
for select to authenticated using (exists (select 1 from public.admin_users au where au.user_id = (select auth.uid())));

revoke all on public.admin_users, public.products, public.orders, public.tracking_events from anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert on public.orders, public.tracking_events to anon, authenticated;
grant select on public.admin_users, public.orders, public.tracking_events to authenticated;
grant insert, update, delete on public.products to authenticated;
grant update on public.orders to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.products (id,title,variant_name,price,currency,image_url,stock_quantity,active,sort_order)
values
  ('marmore','Kit 10 Peças Colinox','Mármore',87.90,'BRL','cart-marmore.png',null,true,1),
  ('quartzo','Kit 10 Peças Colinox','Quartzo',79.90,'BRL','assets/products/quartzo.webp',null,true,2),
  ('grafite','Kit 10 Peças Colinox','Grafite',89.90,'BRL','assets/products/grafite.webp',null,true,3),
  ('oliva','Kit 10 Peças Colinox','Oliva',89.90,'BRL','assets/products/oliva.webp',null,true,4)
on conflict (id) do update set
  title = excluded.title,
  variant_name = excluded.variant_name,
  price = excluded.price,
  currency = excluded.currency,
  image_url = coalesce(excluded.image_url, public.products.image_url),
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();
