create table if not exists public.pushcut_endpoints (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  event_type text not null check (event_type in ('order_created', 'order_paid')),
  url_hint text not null default 'api.pushcut.io/••••••/notifications/••••••',
  url_fingerprint text not null check (char_length(url_fingerprint) = 64),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (url_fingerprint, event_type)
);

create table if not exists public.pushcut_deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  endpoint_id uuid not null references public.pushcut_endpoints(id) on delete cascade,
  event_type text not null check (event_type in ('order_created', 'order_paid')),
  event_key text not null,
  status text not null default 'processing' check (status in ('processing', 'delivered', 'failed')),
  response_status integer,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  delivered_at timestamptz,
  unique (order_id, endpoint_id, event_type),
  unique (event_key)
);

alter table public.pushcut_endpoints enable row level security;
alter table public.pushcut_deliveries enable row level security;

create policy "Admins can read PushCut endpoints" on public.pushcut_endpoints
for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Admins can read PushCut deliveries" on public.pushcut_deliveries
for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create or replace function public.set_pushcut_url(p_endpoint_id uuid, p_url text)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
declare secret_name text := 'pushcut_endpoint_' || p_endpoint_id::text;
begin
  if p_url is null or char_length(trim(p_url)) < 30 or char_length(p_url) > 1000 then
    raise exception 'URL do PushCut inválida';
  end if;
  if not exists (select 1 from public.pushcut_endpoints where id = p_endpoint_id) then
    raise exception 'Destino do PushCut não encontrado';
  end if;
  select id into secret_id from vault.secrets where name = secret_name;
  if secret_id is null then
    perform vault.create_secret(trim(p_url), secret_name, 'Webhook secreto do PushCut');
  else
    perform vault.update_secret(secret_id, trim(p_url), secret_name, 'Webhook secreto do PushCut');
  end if;
end;
$$;

create or replace function public.get_pushcut_url(p_endpoint_id uuid)
returns text language sql stable security definer set search_path = ''
as $$
  select decrypted_secret from vault.decrypted_secrets
  where name = 'pushcut_endpoint_' || p_endpoint_id::text limit 1;
$$;

create or replace function public.delete_pushcut_url(p_endpoint_id uuid)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
begin
  select id into secret_id from vault.secrets where name = 'pushcut_endpoint_' || p_endpoint_id::text;
  if secret_id is not null then delete from vault.secrets where id = secret_id; end if;
end;
$$;

create or replace function public.claim_pushcut_delivery(p_order_id bigint, p_endpoint_id uuid, p_event_type text)
returns bigint language plpgsql security definer set search_path = ''
as $$
declare delivery_id bigint;
declare stable_key text := 'pushcut:' || p_event_type || ':' || p_order_id::text || ':' || p_endpoint_id::text;
begin
  if p_event_type not in ('order_created', 'order_paid') then
    raise exception 'Evento do PushCut inválido';
  end if;
  insert into public.pushcut_deliveries (order_id, endpoint_id, event_type, event_key, status)
  values (p_order_id, p_endpoint_id, p_event_type, stable_key, 'processing')
  on conflict do nothing
  returning id into delivery_id;
  return delivery_id;
end;
$$;

revoke all on function public.set_pushcut_url(uuid, text) from public, anon, authenticated;
revoke all on function public.get_pushcut_url(uuid) from public, anon, authenticated;
revoke all on function public.delete_pushcut_url(uuid) from public, anon, authenticated;
revoke all on function public.claim_pushcut_delivery(bigint, uuid, text) from public, anon, authenticated;
grant execute on function public.set_pushcut_url(uuid, text) to service_role;
grant execute on function public.get_pushcut_url(uuid) to service_role;
grant execute on function public.delete_pushcut_url(uuid) to service_role;
grant execute on function public.claim_pushcut_delivery(bigint, uuid, text) to service_role;

create index if not exists pushcut_endpoints_active_event_idx on public.pushcut_endpoints (event_type) where active;
create index if not exists pushcut_deliveries_endpoint_status_idx on public.pushcut_deliveries (endpoint_id, status);

grant select on public.pushcut_endpoints, public.pushcut_deliveries to authenticated;
grant select, insert, update, delete on public.pushcut_endpoints, public.pushcut_deliveries to service_role;
grant usage, select on sequence public.pushcut_deliveries_id_seq to service_role;


