create table if not exists public.marketing_integrations (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('google', 'meta', 'tiktok')),
  name text not null check (char_length(name) between 2 and 80),
  tracking_id text not null check (char_length(tracking_id) between 2 and 200),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_deliveries (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  integration_id uuid not null references public.marketing_integrations(id) on delete cascade,
  event_name text not null default 'purchase' check (event_name = 'purchase'),
  status text not null default 'processing' check (status in ('processing', 'delivered', 'failed')),
  response_status integer,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, integration_id, event_name)
);

alter table public.marketing_integrations enable row level security;
alter table public.marketing_deliveries enable row level security;

create policy "Admins can read marketing integrations" on public.marketing_integrations
for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));
create policy "Admins can read marketing deliveries" on public.marketing_deliveries
for select to authenticated using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create or replace function public.set_marketing_secret(p_integration_id uuid, p_secret text)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
declare secret_name text := 'marketing_integration_' || p_integration_id::text;
begin
  if p_secret is null or char_length(trim(p_secret)) < 8 or char_length(p_secret) > 1000 then
    raise exception 'Credencial de rastreamento inválida';
  end if;
  if not exists (select 1 from public.marketing_integrations where id = p_integration_id) then
    raise exception 'Integração não encontrada';
  end if;
  select id into secret_id from vault.secrets where name = secret_name;
  if secret_id is null then
    perform vault.create_secret(trim(p_secret), secret_name, 'Credencial server-side de rastreamento');
  else
    perform vault.update_secret(secret_id, trim(p_secret), secret_name, 'Credencial server-side de rastreamento');
  end if;
end;
$$;

create or replace function public.get_marketing_secret(p_integration_id uuid)
returns text language sql stable security definer set search_path = ''
as $$
  select decrypted_secret from vault.decrypted_secrets
  where name = 'marketing_integration_' || p_integration_id::text limit 1;
$$;

create or replace function public.delete_marketing_secret(p_integration_id uuid)
returns void language plpgsql security definer set search_path = ''
as $$
declare secret_id uuid;
begin
  select id into secret_id from vault.secrets where name = 'marketing_integration_' || p_integration_id::text;
  if secret_id is not null then delete from vault.secrets where id = secret_id; end if;
end;
$$;

create or replace function public.claim_marketing_delivery(p_order_id bigint, p_integration_id uuid)
returns bigint language plpgsql security definer set search_path = ''
as $$
declare delivery_id bigint;
begin
  insert into public.marketing_deliveries (order_id, integration_id, event_name, status)
  values (p_order_id, p_integration_id, 'purchase', 'processing')
  on conflict (order_id, integration_id, event_name) do update
    set status = 'processing', response_status = null, last_error = null, updated_at = now()
    where public.marketing_deliveries.status = 'failed'
  returning id into delivery_id;
  return delivery_id;
end;
$$;

revoke all on function public.set_marketing_secret(uuid, text) from public, anon, authenticated;
revoke all on function public.get_marketing_secret(uuid) from public, anon, authenticated;
revoke all on function public.delete_marketing_secret(uuid) from public, anon, authenticated;
revoke all on function public.claim_marketing_delivery(bigint, uuid) from public, anon, authenticated;
grant execute on function public.set_marketing_secret(uuid, text) to service_role;
grant execute on function public.get_marketing_secret(uuid) to service_role;
grant execute on function public.delete_marketing_secret(uuid) to service_role;
grant execute on function public.claim_marketing_delivery(bigint, uuid) to service_role;

grant select on public.marketing_integrations, public.marketing_deliveries to authenticated;
